model: # Edit model config referring to the follow link: https://huggingface.co/docs/transformers/master/en/model_doc/auto#transformers.AutoModelForPreTraining
  attention_probs_dropout_prob: 0.1
  bos_token_id: 0
  eos_token_id: 2
  pad_token_id: 1
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  hidden_size: 512
  initializer_range: 0.02
  intermediate_size: 2048
  layer_norm_eps: 1e-05
  max_position_embeddings: 512
  model_type: "bart" # Choose a model type in pretrain_language_model.py.
  num_attention_heads: 8
  num_hidden_layers: 4
  type_vocab_size: 1
  vocab_size: 30522
data:
  data_dir: "datasets/bart" # Fill in the path of a output of running serialize_corpora.py.
  test_size: 0.0 # If you set this argument, arguments must be floating type. (e.g. 0.01)
collator:
  pad_to_multiple_of: 8
  masking_rate : 0.3
  span_length_param : 3.0
training: # Edit training config referring to the follow link: https://huggingface.co/docs/transformers/master/en/main_classes/trainer#transformers.TrainingArguments
  output_dir: "checkpoints/bart" # Fill in the path which is used to save checkpoints.
  overwrite_output_dir: True # If you use multi-node, set this True.
  do_train: True
  do_eval: False
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  max_steps: 1000000
  lr_scheduler_type: "linear"
  warmup_steps: 10000
  logging_strategy: "steps"
  logging_steps: 500
  evaluation_strategy: "no"
  eval_steps: 0
  save_strategy: "steps"
  save_steps: 10000
  save_total_limit: 5
  seed: 42
  fp16: False
  sharded_ddp: False
  no_cuda: True
  deepspeed:
  gradient_checkpointing: False
